/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CLASS.JDBC;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Mayura Lakshan
 */

public class Admin_UI extends javax.swing.JFrame {

    /**
     * Creates new form Admin_UI
     */
    JDBC jdbc=new JDBC();
    int WHO;
    
    public void savedata(int ID){
    
        if(ID==0){
            if(!(_old.getText().equals("")) & !(_new.getText().equals(""))){
                String OLD=_old.getText();
                
                try {
                    String Sql="SELECT admin_id FROM admin WHERE password='"+OLD+"'";
                    ResultSet RS=jdbc.getData(Sql);
                    if(RS.next()){
                        String ID2=RS.getString("admin_id");
                        String NEW=_new.getText();
                        String Sql2="UPDATE admin SET password='"+NEW+"' WHERE admin_id='"+ID2+"'";
                        int I=jdbc.putData(Sql2);
                        if(I==1){
                            JOptionPane.showMessageDialog(this,"Successfully Updated It Will Change After Application Restarted !");
                            dispose();
                           
                            
                        }else{
                            JOptionPane.showMessageDialog(this,"Can't Update Pleaase Retry !");
                            clear();
                        }
                    }else{
                        JOptionPane.showMessageDialog(this,"Old Password Is Incorrect  !");
                        clear();
                    }
                
            } catch (Exception e) {
                    System.out.println(e);
            }
                
        }else{
            JOptionPane.showMessageDialog(this,"Can't Leave Any Field Empty !");
            clear();
        }
        
        
        
        }
        
        
        if(ID==1){
            
        
            
            if(!(_old.getText().equals("")) & !(_new.getText().equals(""))){
                String OLD=_old.getText();
                
                try {
                    String Sql="SELECT admin_id FROM admin WHERE password='"+OLD+"'";
                    ResultSet RS=jdbc.getData(Sql);
                    if(RS.next()){
                        String ID2=RS.getString("admin_id");
                        String NEW=_new.getText();
                        String Sql2="UPDATE admin SET password='"+NEW+"' WHERE admin_id='"+ID2+"'";
                        int I=jdbc.putData(Sql2);
                        if(I==1){
                            JOptionPane.showMessageDialog(this,"Successfully Updated It Will Change After Application Restarted !");
                            dispose();
                this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(this,"Can't Update Pleaase Retry !");
                            clear();
                        }
                    }else{
                        JOptionPane.showMessageDialog(this,"Old Password Is Incorrect  !");
                        clear();
                    }
                
            } catch (Exception e) {
                    System.out.println(e);
            }
                
        }else{
            JOptionPane.showMessageDialog(this,"Can't Leave Any Field Empty !");
            clear();
        }
        
        
        
        }
    
    }
    
    public Admin_UI() {
        initComponents();
        clear();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/home.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        _old = new javax.swing.JTextField();
        _new = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        _U = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CHANGE USER PASSWORD");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Old Password :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("New Password :");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add16.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close_x16.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        _old.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _old.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        _old.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _oldActionPerformed(evt);
            }
        });
        _old.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _oldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _oldKeyReleased(evt);
            }
        });

        _new.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _new.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        _new.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _newKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _newKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("User :");

        _U.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _U.setForeground(new java.awt.Color(0, 153, 0));
        _U.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        _U.setToolTipText("");
        _U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _UActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(241, 196, 15));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 68, 173));
        jLabel1.setText("Change User Password");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(_U, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(_new, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(_old)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_U, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_old, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(_new, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(175, 175, 175))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void _UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__UActionPerformed
        String A=_U.getSelectedItem().toString();
        if(A.equals("Admin")){

            WHO=1;

        }
        if(A.equals("User")){

            WHO=0;

        }
        _old.grabFocus();
    }//GEN-LAST:event__UActionPerformed

    private void _newKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__newKeyReleased

    }//GEN-LAST:event__newKeyReleased

    private void _newKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__newKeyPressed
        if(evt.getKeyCode()==10){
            if(WHO==0 | WHO==1){
                savedata(WHO);
            }else{
                JOptionPane.showMessageDialog(this,"Please Select User First !");
                clear();

            }
        }
    }//GEN-LAST:event__newKeyPressed

    private void _oldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__oldKeyReleased
        
    }//GEN-LAST:event__oldKeyReleased

    private void _oldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__oldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__oldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(WHO==0 | WHO==1){
            savedata(WHO);
        }else{
            JOptionPane.showMessageDialog(this,"Please Select User First !");
            clear();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void _oldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__oldKeyPressed
        if(evt.getKeyCode()==10){
            _new.grabFocus();
        }
    }//GEN-LAST:event__oldKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> _U;
    private javax.swing.JTextField _new;
    private javax.swing.JTextField _old;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        _old.setText("");
        _new.setText("");
        WHO=3;
        _old.grabFocus();
    }
}
