/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CLASS.JDBC;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Mayura Lakshan
 */
public final class Settings_UI extends javax.swing.JFrame {

    /**
     * Creates new form Settings_UI
     */
    JDBC jdbc =JDBC.getInstance();

    public boolean savedata() {
        boolean Val = false;
        String NF = _NF.getText();
        String NB = _NB.getText();
        String CN = _CN.getText();
        String AD = _AD.getText();

        if (!(_NF.getText().equals("")) & !(_NB.equals("")) & !(_CN.getText().equals("")) & !(_AD.equals(""))) {

            try {
                String SQL = "UPDATE details SET nf='" + NF + "' ,nb='" + NB + "', cn='" + CN + "' ,ad='" + AD + "' WHERE id='1'";
                int V = jdbc.putData(SQL);
                if (V == 1) {
                    Val = true;

                }
            } catch (Exception e) {
                System.out.println(e);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Please Fill All Fields !");

        }

        return Val;

    }

    public void getdata() {
        String SQL = "SELECT * FROM details WHERE id='1'";
        try {
            ResultSet data = jdbc.getData(SQL);
            if (data.next()) {
                _NF.setText(data.getString("nf"));
                _NB.setText(data.getString("nb"));
                _CN.setText(data.getString("cn"));
                _AD.setText(data.getString("ad"));

            } else {
                JOptionPane.showMessageDialog(rootPane, "No Data Found Enter New Data And Save !");
                clear();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "cant load data fill and save again !");
            clear();
        }

    }

    public void clear() {
        _NB.setText("");
        _NF.setText("");
        _CN.setText("");
        _AD.setText("");
        _NF.grabFocus();

    }

    public Settings_UI() {
        initComponents();

        clear();
        getdata();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/home.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        _NB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        _NF = new javax.swing.JTextField();
        _CN = new javax.swing.JTextField();
        _AD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CHANGE SHOP DETAILS");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Contact Number :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Adress :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Grocery Name For Bill  :");

        _NB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        _NB.setForeground(new java.awt.Color(39, 174, 96));
        _NB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _NBActionPerformed(evt);
            }
        });
        _NB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _NBKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _NBKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Grocery Name :");

        _NF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        _NF.setForeground(new java.awt.Color(39, 174, 96));
        _NF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _NFKeyPressed(evt);
            }
        });

        _CN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        _CN.setForeground(new java.awt.Color(39, 174, 96));
        _CN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _CNKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _CNKeyTyped(evt);
            }
        });

        _AD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        _AD.setForeground(new java.awt.Color(39, 174, 96));
        _AD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _ADKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close_x16.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add16.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setText("Personalize");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_NF, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                            .addComponent(_AD)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(_NB)
                            .addComponent(_CN)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(_NF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(_NB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void _NFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__NFKeyPressed
        if (evt.getKeyCode() == 10) {

            _NB.grabFocus();
        }
    }//GEN-LAST:event__NFKeyPressed

    private void _NBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__NBKeyPressed
        if (evt.getKeyCode() == 10) {

            _CN.grabFocus();
        }
    }//GEN-LAST:event__NBKeyPressed

    private void _NBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__NBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__NBActionPerformed

    private void _CNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__CNKeyPressed
        if (evt.getKeyCode() == 10) {

            _AD.grabFocus();
        }
    }//GEN-LAST:event__CNKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == 10) {

        }
    }//GEN-LAST:event_formKeyPressed

    private void _ADKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__ADKeyPressed
        if (evt.getKeyCode() == 10) {

            boolean V = savedata();
            if (V) {
                JOptionPane.showMessageDialog(rootPane, "Data Saved ! Data Will be change after system restart.");
                dispose();
                
                
                
               

            } else {

                JOptionPane.showMessageDialog(rootPane, "Can't Save Data Please Re Try !");
                clear();
            }

        }
    }//GEN-LAST:event__ADKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean V = savedata();
        if (V) {
            JOptionPane.showMessageDialog(rootPane, "Data Saved !");
            System.exit(0);
               
            
                


        } else {

            JOptionPane.showMessageDialog(rootPane, "Cant Save Data Please Re Try !");
            clear();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void _NBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__NBKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event__NBKeyTyped

    private void _CNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__CNKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
        if(_CN.getText().length()== 10){
            evt.consume();
        }
    }//GEN-LAST:event__CNKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _AD;
    private javax.swing.JTextField _CN;
    private javax.swing.JTextField _NB;
    private javax.swing.JTextField _NF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
